### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by gutiman** [JonhCR/FirmaXadesEpes#5]
Buenos días.

Intenté correr esto:

java -jar firmar-xades.jar cert.p12 1234 mensaje_receptor.xml mensaje_receptor_firmado.xml

Todos los archivos (el .jar, el .p12 y el xml estan en la misma carpeta donde estoy corriendo ese comando), pero me retorna:

java.lang.NullPointerException
        at com.solutionscr.firmaxades.Signer.writeXMLToFile(Signer.java:142)
        at com.solutionscr.firmaxades.Signer.signWithoutIDEnveloped(Signer.java:114)
        at com.solutionscr.firmaxades.Signer.sign(Signer.java:73)
        at com.solutionscr.firmaxades.Signer.main(Signer.java:64)

Que podrá ser?

**Comment by gutiman** [comment]
Ya encontré solución:

java -jar firmar-xades.jar ./cert.p12 1234 ./mensaje_receptor.xml ./mensaje_receptor_firmado.xml
